version: '3.3'
services:

  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net

  comment_db:
    image: mongo:3.2
    volumes:
      - comment_db:/data/db
    networks:
      - back_net
     
  ui:
#    build: ./ui
    image: ${USERNAME}/ui:${UI_SERVICE_VERSION}
    ports:
      - 9292:${UI_EXT_PORT}/tcp
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
     
  post:
#    build: ./post-py
    image: ${USERNAME}/post:${POST_SERVICE_VERSION}
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
        
    networks:
      - back_net
      - front_net
     
  comment:
#    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_SERVICE_VERSION}
    networks:
      - back_net
      - front_net
     
volumes:
  post_db:
  comment_db:

networks:
  back_net:
  front_net:
