version: '3.3'
services:

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net
      - front_net

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - back_net
      - front_net

  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net

  comment_db:
    image: mongo:3.2
    volumes:
      - comment_db:/data/db
    networks:
      - back_net
     
  ui:
#    build: ./ui
    image: ${USERNAME}/ui:${UI_SERVICE_VERSION}
    ports:
      - 9292:${UI_EXT_PORT}/tcp
    networks:
      - front_net
     
  post:
#    build: ./post-py
    image: ${USERNAME}/post:${POST_SERVICE_VERSION}
    networks:
      - back_net
      - front_net
     
  comment:
#    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_SERVICE_VERSION}
    networks:
      - back_net
      - front_net
     
volumes:
  prometheus_data:
  post_db:
  comment_db:

networks:
  back_net:
  front_net:
