version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
       - back_net
     
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_SERVICE_VERSION}
    ports:
      - 9292:${UI_EXT_PORT}/tcp
    networks:
       - front_net
     
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_SERVICE_VERSION}
    networks:
       - back_net
       - front_net
     
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_SERVICE_VERSION}
    networks:
       - back_net
       - front_net
     
volumes:
  post_db:

networks:
  back_net:
  front_net:
